# Generated by Django 5.2.4 on 2025-08-26 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(editable=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_tome', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomes', to='produit.manga')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquisition', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_tomes', to=settings.AUTH_USER_MODEL)),
                ('tome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possesseurs', to='produit.tome')),
            ],
            options={
                'unique_together': {('user', 'tome')},
            },
        ),
    ]
