# Generated by Django 5.2.4 on 2025-08-26 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tome',
            name='possesseurs',
            field=models.ManyToManyField(blank=True, related_name='tomes_possedes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CollectionTome',
        ),
    ]
