# Generated by Django 5.2.4 on 2025-09-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_tome_possesseurs_delete_collectiontome'),
    ]

    operations = [
        migrations.AddField(
            model_name='tome',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='karlBouvier/'),
        ),
    ]
