# Generated by Django 5.2.4 on 2025-09-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='tomes',
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='produit.shoppingcart')),
                ('tome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.tome')),
            ],
            options={
                'unique_together': {('cart', 'tome')},
            },
        ),
    ]
