# Generated by Django 5.2.4 on 2025-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0008_category_manga_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='category',
        ),
        migrations.AddField(
            model_name='manga',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='mangas', to='produit.category'),
        ),
    ]
