# Generated by Django 5.2.4 on 2025-10-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0009_remove_manga_category_manga_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('data', models.JSONField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_client_secret', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('succeeded', 'Réussi'), ('failed', 'Échec'), ('canceled', 'Annulé'), ('requires_action', 'Action requise')], default='pending', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='eur', max_length=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('stripe_metadata', models.JSONField(blank=True, default=dict)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='produit.commande')),
            ],
        ),
    ]
